CREATE TABLE 'REVIEW' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'NAME' VARCHAR(100) NOT NULL,
  'RATING' VARCHAR(10) NOT NULL,
  'DATE' DATE NOT NULL,
  'TEXT' VARCHAR(1000) NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE)
  INDEX 'FK_PRODUCT_DETAIL_ID_REVIEW' ('PRODUCT_DETAIL_ID' ASC) VISIBLE,
  CONSTRAINT 'FK_PRODUCT_DETAIL_ID_REVIEW'
    FOREIGN KEY ('PRODUCT_DETAIL_ID')
    REFERENCES 'PRODUCT_DETAIL' ('ID')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

  
CREATE TABLE 'AMANITY' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'NAME' VARCHAR(50) NOT NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE)
  INDEX 'FK_PRODUCT_DETAIL_ID_AMANITY' ('PRODUCT_DETAIL_ID' ASC) VISIBLE,
  CONSTRAINT 'FK_PRODUCT_DETAIL_ID_AMANITY'
    FOREIGN KEY ('PRODUCT_DETAIL_ID')
    REFERENCES 'PRODUCT_DETAIL' ('ID')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

 
CREATE TABLE 'IMAGES' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'PICTURE' BLOB NOT NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE)
  INDEX 'FK_PRODUCT_DETAIL_ID_IMAGES' ('PRODUCT_DETAIL_ID' ASC) VISIBLE,
  CONSTRAINT 'FK_PRODUCT_DETAIL_ID_IMAGES'
    FOREIGN KEY ('PRODUCT_DETAIL_ID')
    REFERENCES 'PRODUCT_DETAIL' ('ID')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

  
CREATE TABLE 'PRODUCT_DETAIL' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'ADDRESS' VARCHAR(200) NOT NULL,
  'RATING' DOUBLE NOT NULL,
  'SLEEPS' INT NOT NULL,
  'BEDROOMS' INT NOT NULL,
  'BATHROOMS' INT NOT NULL,
  'DESCRIPTION' VARCHAR(1000) NULL,
  'AMANITY_ID' INT NULL,
  'REVIEW_ID' INT NULL,
  'IMAGE_ID' INT NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE,
  INDEX 'FK_PRODUCT_PRODUCT_DETAIL' ('PRODUCT_ID' ASC) VISIBLE,
  CONSTRAINT 'FK_PRODUCT_PRODUCT_DETAIL'
    FOREIGN KEY ('PRODUCT_ID')
    REFERENCES 'PRODUCT' ('ID')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
