CREATE TABLE 'PRODUCT' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'NAME' VARCHAR(100) NOT NULL,
  'PRICE' DECIMAL(9,3) NOT NULL,
  'TYPE' VARCHAR(20) NOT NULL,
  'AREA' INT NOT NULL,
  'LOCATION' VARCHAR(50) NOT NULL,
  'IMAGE' BLOB NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE);
  
INSERT INTO PRODUCT (NAME, PRICE, TYPE, AREA, LOCATION) VALUES ('Hidden Sunset', 456.000, 'HOUSE', 232, 'New York');