CREATE TABLE 'REVIEW' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'NAME' VARCHAR(100) NOT NULL,
  'RATING' VARCHAR(1) NOT NULL,
  'DATE' DATE NOT NULL,
  'TEXT' VARCHAR(1000) NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE);

  
CREATE TABLE 'AMANITY' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'NAME' VARCHAR(50) NOT NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE);

 
CREATE TABLE 'IMAGES' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'PICTURE' BLOB NOT NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE);

  
CREATE TABLE 'PRODUCT_DETAIL' (
  'ID' INT NOT NULL AUTO_INCREMENT,
  'ADDRESS' VARCHAR(200) NOT NULL,
  'RATING' DECIMAL(2,2) NOT NULL,
  'SLEEPS' INT NOT NULL,
  'BEDROOMS' INT NOT NULL,
  'BATHROOMS' INT NOT NULL,
  'DESCRIPTION' VARCHAR(1000) NULL,
  'AMANITY_ID' INT NULL,
  'REVIEW_ID' INT NULL,
  'IMAGE_ID' INT NULL,
  PRIMARY KEY ('ID'),
  UNIQUE INDEX 'ID_UNIQUE' ('ID' ASC) VISIBLE,
  INDEX 'FK_AMANITY_idx' ('AMANITY_ID' ASC) VISIBLE,
  INDEX 'FK_REVIEW_idx' ('REVIEW_ID' ASC) VISIBLE,
  INDEX 'FK_IMAGE_idx' ('IMAGE_ID' ASC) VISIBLE,
  CONSTRAINT 'FK_AMANITY'
    FOREIGN KEY ('AMANITY_ID')
    REFERENCES 'AMANITY' ('ID')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'FK_REVIEW'
    FOREIGN KEY ('REVIEW_ID')
    REFERENCES 'REVIEW' ('ID')
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT 'FK_IMAGE'
    FOREIGN KEY ('IMAGE_ID')
    REFERENCES 'IMAGES' ('ID')
    ON DELETE CASCADE
    ON UPDATE CASCADE);
  
ALTER TABLE 'PRODUCT' 
ADD COLUMN 'PRODUCT_DETAIL_ID' INT NULL AFTER 'type',
ADD INDEX 'FK_PRODUCT_DETAIL_idx' ('PRODUCT_DETAIL_ID' ASC) VISIBLE;

;

ALTER TABLE 'PRODUCT' 
ADD CONSTRAINT 'FK_PRODUCT_DETAIL'
  FOREIGN KEY ('PRODUCT_DETAIL_ID')
  REFERENCES 'PRODUCT_DETAIL' ('ID')
  ON DELETE CASCADE
  ON UPDATE NO ACTION;
